### ISSUE TITLE
Agenda items for March 19th meeting

### ISSUE THREAD

**Issue by hans-schmidt** [kentbull/rvn-agendas#9]
Some items left over from last week:

	-Which non-code things should the Foundation control and spend money on? Seeds? Websites?
	-Can someone put together a list of all the major Ravencoin-related websites & github accounts and who owns them or has control?
		-What about social media accounts (Discord, Telegram, Reddit, etc) and who owns, controls, moderates them?
		-Post them on the Foundation website
		-The point of the exercise is transparency, not to gain control.
	-Should we fund someone a modest amount to go through the Discord helpdesk and put together & maintain an organized FAQ for noobs?
	-Should we fund someone a modest amount to keep Raven.wiki updated? 

Also:

	-Non-profit corporations formed to support communities usually publish their Articles of Incorporation and their Bylaws on their website. Will the Foundation do that?

	-What is the plan regarding Tron's proposal for decentralized Foundation governance? Was that all contingent on a mining tax? see: https://discord.com/channels/429127343165145089/637386139279556659/773220055265181741

	-Procedure for SIG gneration of bounties. The Electrum-SIG will soon want to put bounties on some intermediate milestones.

**Comment by kentbull** [comment]
@hans-schmidt great additions. Will you submit a PR?

**Comment by kentbull** [comment]
These were added in just now
